### ISSUE TITLE
ember new -- doesn't work out of the box

### ISSUE THREAD

**Issue by xpat** [glimmerjs/glimmer-blueprint#77] opened 2018-01-07 17:40 UTC
This is similar to issue #74 (ember s doesn't work out of the box).

The Glimmer quickstart "my-app" instructions never work for me.  After reading any number of issues (open and closed), and trying to run the command in the various ways, I still can't figure out what's going wrong.  Here's a link to the error message I got when running the command as instructed ($ ember new my-app -b @glimmer/blueprint) [error message no flag](https://gist.github.com/xpat/6e2e64c3db0d486cd10451becaebadeb) and a link to the error message I got when using the flag --yarn=false. [error message with flag](https://gist.github.com/xpat/642e2dab297d379b9748daf74b602cb9#file-error-dump-3325d68f6ea29800004f7e787ff97eaa-log).

**Comment by rmmmp** [comment] 2018-01-08 13:37
Same here. I think the issue is because it's trying to download https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node which is a broken link.

**Comment by xpat** [comment] 2018-01-09 01:03
> Same here. I think the issue is because it's trying to download https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node which is a broken link.

The two error logs that I initially posted don't contain a reference to sass...binding.node, @rmmmp.  This one does (from a fresh attempt on another computer): [error message 3](https://gist.github.com/xpat/c303e168dd4eac1da2ec4c42a1ac0f3c).

Incidentally, I finally got the elusive glimmer/blueprint quickstart example to work on one of three computers. Here is a link to some related [bash history.txt](https://github.com/glimmerjs/glimmer-blueprint/files/1613536/history.txt) that preceeded the successful runs.  Anybody know where to find the log files of a successful run?

**Comment by rmmmp** [comment] 2018-01-09 01:46
I believe my error would only happen if you don't have yarn installed. When I had yarn, my error was the same with yours. Although I'm seeing in slack that there's some people having the same problem too. I do wonder if this is the right repo to post the issue or to somewhere else.

**Comment by xpat** [comment] 2018-01-09 02:16
@rmmmp all my attempts (successful and failed) are on computers running linux ubuntu 16.04, all with Yarn installed.  Sometimes I run the command with the option --yarn=false.

**Comment by rmmmp** [comment] 2018-01-09 03:08
I tried downgrading to node 6.12.2 and it worked

**Comment by headquarters** [comment] 2018-02-08 19:42
Ran into the same problem on macOS Sierra, node 8.2.1, npm 5.5.1, ember-cli 2.18.1. Here is the [output log](https://gist.github.com/headquarters/62a3526a6155885c319de3a5553e8e8b). 

The following command consistently failed: `ember new glimmer-components -b @glimmer/blueprint`
However, `ember new glimmer-components -b @glimmer/blueprint --yarn=false` worked. I'm running yarn v1.3.2.

**Comment by t-sauer** [comment] 2018-02-08 20:07
You should upgrade to ember-cli 2.18.2. the problem should be fixed there.

**Closed** 2018-02-09 01:16 UTC
